title: Ivan Blog
description: Blogs about IT technical articles.
show_downloads: true

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://ivanhan0511.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
  ivan-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
Ivan-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Ivan Han"
image: /thumbnail-jumbo.png
twitter:
  username: ivanhan0511
  site: http://ivanhan0511.github.io/blog
#facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  #app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
  #admins:
